//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWCF_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDATHANGs = new HashSet<CTDATHANG>();
            this.HINHANHs = new HashSet<HINHANH>();
           
        }
    
        public int MaSP { get; set; }
        public string TenSp { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string Hinh { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> SoluongBan { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaTTSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATHANG> CTDATHANGs { get; set; }
        public virtual DANHMUC_SP DANHMUC_SP { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual TRANGTHAISP TRANGTHAISP { get; set; }
        public virtual SANPHAM SANPHAM1 { get; set; }
        public virtual SANPHAM SANPHAM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANHs { get; set; }

       
        
    }
}
